export const FETCH_PHONES_START = 'FETC_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETC_PHONES_SUCCESS';
export const FETCH_PHONES_FAILURE = 'FETC_PHONES_FAILURE';

export const LOAD_MORE_PHONES_START = 'LOAD_MORE_PHONES_START';
export const LOAD_MORE_PHONES_SUCCESS = 'LOAD_MORE_PHONES_SUCCESS';
export const LOAD_MORE_PHONES_FAILURE = 'LOAD_MOREPHONES_FAILURE';